# build stage
FROM node:lts-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ENV $(cat .env.production | grep -v '^#' | xargs)

RUN npm run build

FROM nginx:stable-alpine as deploy

ENV NODE_ENV production

COPY --from=build /app/build /usr/share/nginx/html 

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3001

CMD ["nginx", "-g", "daemon off;"]