version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
